### PR TITLE
Adding YongJoon Oh user to AWS account

### PR DESCRIPTION
**Pull request by OCEO-YJ**

### CODE REVIEW

**Comment by DwayneJengSage** [comment]
@zaro0508 It looks like the Travis build failed. Did something change with the build system?

**Comment by zaro0508** [comment]
yes, attempting to fix here: https://github.com/Sage-Bionetworks/Bridge-infra/pull/127

**Comment by ahayden** [comment]
Er- did we want this on the develop branch? I merged as I'm here with @OCEO-YJ and we want to move it

**Comment by DwayneJengSage** [comment]
I thought SOP was to merge things into develop first, and then merge to prod?

That said, I'm not sure what the develop branch of Bridge-infra actually does...

**Comment by zaro0508** [comment]
There is an dev AWS account for Bridge and that's what the `develop` branch is for.  This dev account is on standby for when we want to separate Bridge into Dev and Prod, issue https://sagebionetworks.jira.com/browse/BRIDGE-1931

**Pull request merged**
