### PR TITLE
[BRIDGE-2887] give sumologic access to cloudtrail bucket

### PR DESCRIPTION
**Pull request by zaro0508**
Setup a role to allow sumologic to ingest cloudtrail logs.

### CODE REVIEW

**Comment by DwayneJengSage** [comment]
I don't use SumoLogic for CloudTrail. I dunno if anyone else does. Can we simply not have SumoLogic access our CloudTrail bucket?

**Comment by zaro0508** [comment]
> Can we simply not have SumoLogic access our CloudTrail bucket?

This PR is exactly doing that.  It allows sumo access to the bridge prod account's cloudtrail bucket which contains the cloudtrail logs.

**Review by DwayneJengSage — APPROVED** [review]
As per Slack, Aaron uses Sumo Logic for CloudTrail.

**Comment by zaro0508** [comment]
I forgot. we don't need this because we already forward cloudtrail events from bridge to  our logcentral account.  we also already setup sumo to ingest cloudtrail logs from logcentral. search for "Sage+AWS+Logging" in our wiki if you want more info on the setup.

**Pull request closed without merging**
